In [ ]:
!pip install kiteconnect

Collecting kiteconnect
  Downloading kiteconnect-4.2.0-py3-none-any.whl (24 kB)
Collecting service-identity>=18.1.0 (from kiteconnect)
  Downloading service_identity-23.1.0-py3-none-any.whl (12 kB)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.10/dist-packages (from kiteconnect) (2.27.1)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from kiteconnect) (1.16.0)
Collecting pyOpenSSL>=17.5.0 (from kiteconnect)
  Downloading pyOpenSSL-23.2.0-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/59.0 kB 5.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.10/dist-packages (from kiteconnect) (2.8.2)
Collecting autobahn[twisted]==19.11.2 (from kiteconnect)
  Downloading autobahn-19.11.2-py2.py3-none-any.whl (771 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 771.5/771.5 kB 19.1 MB/s eta 0:00:00
Collecting txaio>=18.8.1 (from autobahn[twisted]==19.11.2->kiteconnect)
  Downloading txaio-23.1.1-py2.py3-none-any.whl (30 kB)
Collecting cryptography>=2.7 (from autobahn[twisted]==19.11.2->kiteconnect)
  Downloading cryptography-41.0.1-cp37-abi3-manylinux_2_28_x86_64.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 79.0 MB/s eta 0:00:00
Collecting zope.interface>=3.6.0 (from autobahn[twisted]==19.11.2->kiteconnect)
  Downloading zope.interface-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.0/247.0 kB 24.7 MB/s eta 0:00:00
Collecting Twisted>=12.1.0 (from autobahn[twisted]==19.11.2->kiteconnect)
  Downloading Twisted-22.10.0-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 80.2 MB/s eta 0:00:00
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.18.4->kiteconnect) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.18.4->kiteconnect) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.18.4->kiteconnect) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.18.4->kiteconnect) (3.4)
Requirement already satisfied: attrs>=19.1.0 in /usr/local/lib/python3.10/dist-packages (from service-identity>=18.1.0->kiteconnect) (23.1.0)
Requirement already satisfied: pyasn1 in /usr/local/lib/python3.10/dist-packages (from service-identity>=18.1.0->kiteconnect) (0.5.0)
Requirement already satisfied: pyasn1-modules in /usr/local/lib/python3.10/dist-packages (from service-identity>=18.1.0->kiteconnect) (0.3.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography>=2.7->autobahn[twisted]==19.11.2->kiteconnect) (1.15.1)
Collecting constantly>=15.1 (from Twisted>=12.1.0->autobahn[twisted]==19.11.2->kiteconnect)
  Downloading constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
Collecting incremental>=21.3.0 (from Twisted>=12.1.0->autobahn[twisted]==19.11.2->kiteconnect)
  Downloading incremental-22.10.0-py2.py3-none-any.whl (16 kB)
Collecting Automat>=0.8.0 (from Twisted>=12.1.0->autobahn[twisted]==19.11.2->kiteconnect)
  Downloading Automat-22.10.0-py2.py3-none-any.whl (26 kB)
Collecting hyperlink>=17.1.1 (from Twisted>=12.1.0->autobahn[twisted]==19.11.2->kiteconnect)
  Downloading hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.6/74.6 kB 8.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.10/dist-packages (from Twisted>=12.1.0->autobahn[twisted]==19.11.2->kiteconnect) (4.6.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from zope.interface>=3.6.0->autobahn[twisted]==19.11.2->kiteconnect) (67.7.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography>=2.7->autobahn[twisted]==19.11.2->kiteconnect) (2.21)
Installing collected packages: incremental, constantly, zope.interface, txaio, hyperlink, Automat, Twisted, cryptography, service-identity, pyOpenSSL, autobahn, kiteconnect
Successfully installed Automat-22.10.0 Twisted-22.10.0 autobahn-19.11.2 constantly-15.1.0 cryptography-41.0.1 hyperlink-21.0.0 incremental-22.10.0 kiteconnect-4.2.0 pyOpenSSL-23.2.0 service-identity-23.1.0 txaio-23.1.1 zope.interface-6.0

In [ ]:
from kiteconnect import KiteConnect

# logging.basicConfig(level=logging.DEBUG)
print('here')
kite = KiteConnect(api_key="aygbpvrrcsaybucb")

# Step 1 - Open the below URL and login and collect the request token
# https://kite.zerodha.com/connect/login?v=4&api_key=aygbpvrrcsaybucb
# Step 2 - Run this program and provide the request token
# Step 3 - You would get access token
# Step 4 - Update the access token in KiteSettings.py

# request_token = input("Request Token: ")
# data = kite.generate_session(request_token, api_secret="ant7m5o74v4x0sptg18gx18kzbkl6i5x")
# kite.set_access_token(data["access_token"])
kite.set_access_token("dwICUtJsEQT1OOQQ0nNkc0TxcboFU2Rb")

# print("====================")
# print("Access Token: ",data["access_token"])

here

In [ ]:
import pandas as pd
nse = kite.instruments('NSE')
nse_data = pd.DataFrame(nse)
nse_data

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange
0,264713,1034,HANGSENG BEES-NAV,HANGSENG BEES-NAV,0.0,,0.0,0.00,0,EQ,INDICES,NSE
1,264969,1035,INDIA VIX,INDIA VIX,0.0,,0.0,0.00,0,EQ,INDICES,NSE
2,260617,1018,NIFTY 100,NIFTY 100,0.0,,0.0,0.00,0,EQ,INDICES,NSE
3,264457,1033,NIFTY 200,NIFTY 200,0.0,,0.0,0.00,0,EQ,INDICES,NSE
4,256265,1001,NIFTY 50,NIFTY 50,0.0,,0.0,0.00,0,EQ,INDICES,NSE
...,...,...,...,...,...,...,...,...,...,...,...,...
5494,2916865,11394,ZOTA,ZOTA HEALTH CARE,0.0,,0.0,0.05,1,EQ,NSE,NSE
5495,7436801,29050,ZUARI,ZUARI AGRO CHEMICALS,0.0,,0.0,0.05,1,EQ,NSE,NSE
5496,979713,3827,ZUARIIND,ZUARI INDUSTRIES,0.0,,0.0,0.05,1,EQ,NSE,NSE
5497,2029825,7929,ZYDUSLIFE,ZYDUS LIFESCIENCES,0.0,,0.0,0.05,1,EQ,NSE,NSE
5498,4514561,17635,ZYDUSWELL,ZYDUS WELLNESS,0.0,,0.0,0.05,1,EQ,NSE,NSE

In [ ]:
import pandas as pd
import numpy as np
import time as Time
from datetime import datetime, timedelta, time
import yfinance as yf
import pytz
import warnings
import sys
from IPython.display import clear_output

In [ ]:
warnings.simplefilter(action='ignore', category=FutureWarning)

In [ ]:
def find_missing_elements(list1, list2):
    missing_elements = [element for element in list1 if element not in list2]
    return missing_elements

def extract_strings(input_list):
    output_list = []
    for input_string in input_list:
        split_string = input_string.split('.')
        output_list.append(split_string[0])
    return output_list

In [ ]:
from datetime import datetime, timedelta
import pandas as pd

def calculate_P(df, k, date):
    days = [14, 28, 56, 112, 224, 336, 448, 896]
    P = 0

    for i in range(len(days)):
        mask = (df.index >= (date - timedelta(days=days[i]))) & (df.index <= date)
        data = df.loc[mask]
        value = ((data['high'] - data['open']) * 100 / data['open'] > k).sum()
        P += (2 ** (len(days) - i - 1)) * value

    return P


def calculate_R(df, k, date):
    days = [14, 28, 56, 112, 224, 336, 448, 896]
    R = 0

    for i in range(len(days)):
        mask = (df.index >= (date - timedelta(days=days[i]))) & (df.index <= date)
        data = df.loc[mask]
        value = ((data['high'] - data['open']) * 100 / data['open'] < k).sum()
        R += (2 ** (len(days) - i - 1)) * value

    return R


def calculate_P2(df, k, date):
    days = [14, 28, 56, 112, 224, 336, 448, 896]
    P = 0

    for i in range(len(days)):
        mask = (df.index >= (date - timedelta(days=days[i]))) & (df.index <= date)
        data = df.loc[mask]
        value = ((data['open'] - data['low']) * 100 / data['open'] > k).sum()
        P += (2 ** (len(days) - i - 1)) * value

    return P


def calculate_R2(df, k, date):
    days = [14, 28, 56, 112, 224, 336, 448, 896]
    R = 0

    for i in range(len(days)):
        mask = (df.index >= (date - timedelta(days=days[i]))) & (df.index <= date)
        data = df.loc[mask]
        value = ((data['open'] - data['low']) * 100 / data['open'] < k).sum()
        R += (2 ** (len(days) - i - 1)) * value

    return R

In [ ]:
def get_intraday_margin_sell(symbol):
    order_param_single = [{
            "exchange": "NSE",
            "tradingsymbol": symbol,
            "transaction_type": "SELL",
            "variety": "regular",
            "product": "MIS",
            "order_type": "MARKET",
            "quantity": 1
        }]
    return kite.order_margins(order_param_single)[0]['leverage']

def get_intraday_margin(symbol):

    order_param_single = [{
            "exchange": "NSE",
            "tradingsymbol": symbol,
            "transaction_type": "BUY",
            "variety": "regular",
            "product": "MIS",
            "order_type": "MARKET",
            "quantity": 1
        }]
    return kite.order_margins(order_param_single)[0]['leverage']

def filter_by_margin(input_list, type):
    if(type == 'buy'):
        output = [element for element in input_list if get_intraday_margin(element)==5]
    if(type == 'sell'):
        output = [element for element in input_list if get_intraday_margin_sell(element)==5]
    return output

In [ ]:
from datetime import datetime, timedelta
import pandas as pd

def archive_stock_data(symbol, stock_data, date):
    # print(date)
    # stock_data.head()
    try:
        # Define the timeframes
        timeframes = {"2y": "2y", "1y": "1y", "6m": "6mo", "16w": "16wk", "8w": "8wk", "4w": "4wk", "2w": "2wk", "1w": "1wk"}

        # Calculate the P values for each k
        k_values = [0.25, 0.35, 0.5, 0.75, 1, 1.5, 2, 2.5, 3, 4, 5]
        l_values = [0, 0.1, 0.2, 0.3, 0.5]
        p_values = []
        r_values = []
        p_values2 = []
        r_values2 = []

        for k in k_values:
            p_value = calculate_P(stock_data, k, date)
            p_values.append(p_value)
            p_value2 = calculate_P2(stock_data, k, date)
            p_values2.append(p_value2)

        for l in l_values:
            r_value = calculate_R(stock_data, l, date)
            r_values.append(r_value)
            r_value2 = calculate_R2(stock_data, l, date)
            r_values2.append(r_value2)

        return symbol, stock_data, p_values, r_values, p_values2, r_values2

    except Exception as e:
        print(f"Error fetching data for {symbol}: {e}")
        return symbol, None, None, None, None, None

In [ ]:
def retrieve_stock_data(stock_archive, start_date, end_date):
    # Find the start and end date locations
    strt = None
    end = None
    for i, date in enumerate(stock_archive):
        if date == start_date:
            strt = i
        if date == end_date:
            end = i
            break

    # Check if both start and end date locations are found
    if strt is None or end is None:
        print("Start or end date not found in the stock archive.")
        return None

    # Retrieve the sublist from stock_archive
    sublist = stock_archive[strt:end+1]

    return sublist

In [ ]:
#SUJAL
column_names = ["Code"]
# nifty500 = pd.read_csv("ind_nifty500list.csv", names=column_names)
# nifty500 = pd.read_excel("/content/temp_testing.xlsx", names=column_names)
nifty500 = pd.read_csv("/content/harshad.csv", names=column_names)

symbol = nifty500.Code.to_list()

columns = ['Symbol'] + [f'P{k:.2f}' for k in [0.25, 0.35, 0.5, 0.75, 1, 1.5, 2, 2.5, 3, 4, 5]] + [f'R{k:.2f}' for k in [0, 0.1, 0.2, 0.3, 0.5]]

output_df = pd.DataFrame(columns=columns)
output_df2 = pd.DataFrame(columns=columns)

k_values = [0.25, 0.35, 0.5, 0.75, 1, 1.5, 2, 2.5, 3, 4, 5]
l_values = [0, 0.1, 0.2, 0.3, 0.5]
start_date = datetime(2023, 7, 3)
end_date = datetime(2023, 7, 5)
date_range = pd.date_range(start=start_date, end=end_date)
results=[]

stock_archive = {}
diff = (end_date - start_date).days
# print(diff)
for i in symbol[:3]:
    print("== downloading for symbol:   ", i);
    # a = nse_data[nse_data.tradingsymbol == i].instrument_token.values
    a = nse_data[nse_data.tradingsymbol == i[:-3]].instrument_token.values
    try:
      token=a[0]
    except Exception as e:
      print(e)
      continue
    # df=kite.historical_data(token, str(end_date - timedelta(days=365 * 2 + (end_date - start_date).days)), str(end_date), "day", False, False)
    # df=kite.historical_data(7929, str(end_date - timedelta(days=365 * 2 + (end_date - start_date).days)), str(end_date), "day", False, False)
    df=kite.historical_data(token, str(start_date - timedelta(days=365 * 2)), str(end_date), "day", False, False)
    df = pd.DataFrame(df)
    if(len(df)==0):
      print("no data")
      continue
    df['date'] = pd.to_datetime(df['date']).dt.date
    df = df.set_index('date')
    # print(df)
    stock_archive[i] = df

for date_i in range(diff):
    symbol = nifty500.Code.to_list()
    columns = ['Symbol'] + [f'P{k:.2f}' for k in [0.25, 0.35, 0.5, 0.75, 1, 1.5, 2, 2.5, 3, 4, 5]] + [f'R{k:.2f}' for k in [0, 0.1, 0.2, 0.3, 0.5]]
    output_df = pd.DataFrame(columns=columns)
    output_df2 = pd.DataFrame(columns=columns)
    k_values = [0.25, 0.35, 0.5, 0.75, 1, 1.5, 2, 2.5, 3, 4, 5]
    l_values = [0, 0.1, 0.2, 0.3, 0.5]


    for i in symbol[:3]:
        strt = date_i
        strt_date=(start_date+timedelta(days=strt)).strftime('%Y-%m-%d')
        strt_date = datetime.strptime(strt_date, '%Y-%m-%d').date()
        # print(strt_date)
        try:
          end = len(stock_archive[i]) - (end_date - start_date).days + date_i
          # end = date_i
          # end = (stock_archive['days'][-1]-stock_archive['days'][0]).days - (end_date - start_date).days + date_i
          # end_dat=(start_date+timedelta(days=end)).strftime('%Y-%m-%d')
          # print(end_dat)
        except Exception as e:
          continue
        date = start_date + timedelta(days=date_i)
        # print(date)

        # symbol, stock_data, p_values, r_values, p_values2, r_values2 = archive_stock_data(i, stock_archive[i][strt:end], date.date())
        # symbol, stock_data, p_values, r_values, p_values2, r_values2 = archive_stock_data(i, stock_archive[i][stock_archive[i]['date'].find(start_date):stock_archive[i]['date'].find(end_date)], date.date())
        # symbol, stock_data, p_values, r_values, p_values2, r_values2 = archive_stock_data(i, stock_archive[i].loc[(stock_archive[i].index >= strt_date - pd.DateOffset(years=2)) & (stock_archive[i].index < strt_date)], date.date())
        # stock_archive[i].loc[(stock_archive[i]['date'] >= strt_date - pd.DateOffset(years=2)) & (stock_archive[i]['date'] < strt_date)]
        # selected_data = stock_archive[i].loc[(stock_archive[i].index >= strt_date - pd.DateOffset(years=2)) & (stock_archive[i].index < strt_date)]
        symbol, stock_data, p_values, r_values, p_values2, r_values2 = archive_stock_data(i, stock_archive[i].loc[(stock_archive[i].index >= pd.Timestamp(strt_date) - pd.DateOffset(years=2)) & (stock_archive[i].index < pd.Timestamp(strt_date))], pd.Timestamp(strt_date).date())
        print(stock_archive[i].loc[(stock_archive[i].index >= pd.Timestamp(strt_date) - pd.DateOffset(years=2)) & (stock_archive[i].index < pd.Timestamp(strt_date))])
        # print(symbol)
        # print(stock_data)

        if stock_data is None:
            continue

        output_data = {'Symbol': symbol}
        output_data2 = {'Symbol': symbol}

        for i, p_value in enumerate(p_values):
            output_data[f'P{k_values[i]:.2f}'] = p_value

        for i, p_value in enumerate(p_values2):
            output_data2[f'P{k_values[i]:.2f}'] = p_value

        for i, r_value in enumerate(r_values):
            output_data[f'R{l_values[i]:.2f}'] = r_value

        for i, r_value in enumerate(r_values2):
            output_data2[f'R{l_values[i]:.2f}'] = r_value

        output_df.loc[len(output_df)] = output_data
        output_df2.loc[len(output_df2)] = output_data2

    output_df['Pro'] = 8 * output_df['P2.50'] + 4 * output_df['P3.00'] + 4 * output_df['P1.00'] + 8 * output_df['P5.00']
    output_df['Ris'] = 2 * output_df['R0.50'] + 4 * output_df['R0.30'] + 8 * output_df['R0.10']
    output_df['Val'] = output_df['Pro'] * output_df['Pro'] / (output_df['Ris'] + 1)

    output_df2['Pro'] = 8 * output_df2['P2.50'] + 4 * output_df2['P3.00'] + 4 * output_df2['P1.00'] + 8 * output_df2['P5.00']
    output_df2['Ris'] = 2 * output_df2['R0.50'] + 4 * output_df2['R0.30'] + 8 * output_df2['R0.10']
    output_df2['Val'] = output_df2['Pro'] * output_df2['Pro'] / (output_df2['Ris'] + 1)

    df = output_df.sort_values(output_df.columns[-1], ascending=False)
    df_dash = output_df2.sort_values(output_df2.columns[-1], ascending=False)

    output_df['Val2'] = output_df['Pro'] / (output_df['Ris'] * output_df['Ris'] + 1)
    output_df2['Val2'] = output_df2['Pro'] / (output_df2['Ris'] * output_df2['Ris'] + 1)
    # print(output_df)
    # print(output_df2)

    df2 = output_df.sort_values(output_df.columns[-1], ascending=False)
    df2_dash = output_df2.sort_values(output_df2.columns[-1], ascending=False)

    n = 10  # Assumed no. of stocks to be invested
    symbol1 = df2.iloc[:n, 0].tolist()
    symbol2 = df2_dash.iloc[:n, 0].tolist()


    buy_symbols = find_missing_elements(symbol1, symbol2)
    sell_symbols = find_missing_elements(symbol2, symbol1)
    buy_symbols = extract_strings(buy_symbols)
    sell_symbols = extract_strings(sell_symbols)
    BUY_SYMBOLS = filter_by_margin(buy_symbols, 'buy')
    SELL_SYMBOLS = filter_by_margin(sell_symbols, 'sell')

    new_df = {'Date': date.strftime('%Y-%m-%d'), 'Buy': BUY_SYMBOLS[:3], 'SeLl': SELL_SYMBOLS[:3]}

    results.append(new_df)
    print(date.strftime('%Y-%m-%d'))
# Create a dataframe from the results list
out = pd.DataFrame(results)
out

== downloading for symbol:    ABB.NS

TokenException: ignored

In [ ]:
out.to_csv('/content/nifty200_3.csv', index=False)